version: '3'
services:
  laravel:
    build: .
    container_name: noe_app
    restart: always
    networks:
      - portfolio-noe
      - vps-proxy
    depends_on:
      - db
    expose:
      - 80
      - 443
    volumes:
      - portfolio-noe-storage:/app/storage
    environment:
      VIRTUAL_HOST: noeterrier.fr,www.noeterrier.fr

  db:
    image: mariadb
    container_name: noe_db
    expose:
        - 3306
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
        - portfolio-noe-db:/var/lib/mysql
    restart: always
    networks:
      - portfolio-noe

networks:
  portfolio-noe:
  vps-proxy:
    external:
      name: vps-proxy


volumes:
  portfolio-noe-db:
    driver: local
  portfolio-noe-storage:
    driver: local
    